server:
  port: 9090
  

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
      - id: "backend"
        predicates:
        - Path=/customers
        uri: http://localhost:8080/
      - id: "frontend"
        predicates:
        - Path=/feigncustomers
        uri: http://localhost:8081/
  profiles:
  - gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
